[program:php-fpm]
command=/usr/sbin/php-fpm8.3 --nodaemonize --fpm-config /etc/php/8.3/fpm/php-fpm.conf
autostart=true
autorestart=true
priority=10
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autostart=true
autorestart=true
priority=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:queue]
command=/usr/bin/php8.3 /var/www/minestore/artisan queue:work --queue=high,standard,low,default --sleep=3 --tries=3 --max-time=3600
user=www-data
autostart=true
autorestart=true
priority=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:paynow-queue]
command=/usr/bin/php8.3 /var/www/minestore/artisan queue:work --queue=paynow --sleep=3 --tries=3 --max-time=3600
user=www-data
autostart=true
autorestart=true
priority=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:worker]
command=/usr/bin/php8.3 /var/www/minestore/artisan cron:worker
user=www-data
autostart=true
autorestart=true
priority=40
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:scheduler]
command=/bin/bash -c "while true; do /usr/bin/php8.3 /var/www/minestore/artisan schedule:run; sleep 60; done"
user=www-data
autostart=true
autorestart=true
priority=40
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:discord]
command=/usr/bin/php8.3 /var/www/minestore/artisan discord:run
user=www-data
autostart=true
autorestart=true
priority=50
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:frontend]
command=/bin/bash /var/www/minestore/frontend.sh
user=root
environment=MINESTORE_PATH="/var/www/minestore",PORT="25401",PID_FILE="/var/run/minestore_frontend.pid",LOG_FILE="/var/log/minestore_frontend.log",CHOWN_USER="www-data",NVM_DIR="",PNPM_HOME="/usr/local/share/pnpm"
autostart=true
autorestart=true
priority=60
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
